In [4]:
import numpy as np
glasses = np.load("/clever/northwestern/jianping/CelebA/STGAN/glasses/dataset/glasses.npy")

In [5]:
print(glasses.shape)

(10, 144, 144, 4)


In [6]:
mask = glasses[0,:,:,3]
print(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
print(np.max(mask))

255


In [42]:
import numpy as np
import scipy.misc

#celebA_path = "/clever/northwestern/jianping/CelebA/dataset"
output_path = "dataset"
data_path = "/clever/northwestern/jianping/CelebA/dataset"
data_path_list = [data_path+"/ICDAR2013/ICDAR2013_train/foreground",
                  data_path+"/ICDAR2013/ICDAR2013_test/foreground",
                  data_path+"/ICDAR2015/train/foreground",
                  data_path+"/ICDAR2015/test/foreground",
                  data_path+"/SVT/foreground"]
print(data_path_list)

['/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground', '/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground', '/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground', '/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground', '/clever/northwestern/jianping/CelebA/dataset/SVT/foreground']


In [43]:
import os
whole_data_path = []
for path in data_path_list:
    for fpathe,dirs,fs in os.walk(path):
        for f in fs:
            #print(f)
            if f[-4:] == ".jpg":
                print(os.path.join(fpathe,f))
                whole_data_path.append(os.path.join(fpathe,f))

/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/100_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/100_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/100_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/100_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/101_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/102_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/102_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/102_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/102_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foreground/102_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_train/foregroun

/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_100_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_100_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_100_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_100_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_100_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_101_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_101_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_102_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_102_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2013/ICDAR2013_test/foreground/img_102_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_100_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_100_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_100_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_100_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_101_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_101_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_101_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_101_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_102_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_102_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_102_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_314_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_314_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_315_5.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_316_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_316_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_316_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_482_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_5.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_6.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_483_7.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_484_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_484_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_852_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_852_5.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_853_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_853_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_854_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_854_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_854_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_854_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_855_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_855_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/train/foreground/img_855_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_3.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_4.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_5.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_100_6.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_101_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_101_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_102_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_102_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreg

/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_242_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_243_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_243_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_244_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_244_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_244_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_245_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_245_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_246_0.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_246_1.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreground/img_246_2.jpg
/clever/northwestern/jianping/CelebA/dataset/ICDAR2015/test/foreg

/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_00_1.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_00_0.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_01_0.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_01_1.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_01_2.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_01_3.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_01_4.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_02_0.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_02_1.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_02_2.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_02_3.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_03_0.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_03_1.jpg
/clever/northwestern/jianping/CelebA/dataset/SVT/foreground/00_0

In [5]:
print(len(whole_data_path))

9179


In [8]:
import random
random.shuffle(whole_data_path)

selected = whole_data_path[:50]

In [39]:
img = scipy.misc.imread(selected[0])
final_img = np.zeros((len(selected),img.shape[0],img.shape[1],4),dtype="uint8")
for batch in range(len(selected)):
    img = scipy.misc.imread(selected[batch])
    mask = np.zeros((img.shape[0],img.shape[1],1),dtype="uint8")
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            if img[i,j,0] != 255 and img[i,j,1] != 255 and img[i,j,2] != 255:
                mask[i][j] = 255
    final = np.concatenate((img,mask),axis = 2)
    final_img[batch,:,:,:] = final 


/opt/conda/envs/tf-py35/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.
/opt/conda/envs/tf-py35/lib/python3.5/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  after removing the cwd from sys.path.


In [40]:
print(final_img.shape)

(50, 144, 144, 4)


In [41]:
np.save("{0}/foreground.npy".format(output_path),final_img)

255


(144, 144, 4)
